# Site
name: "Fernando Cejas"
description: "Welcome! I'm Fernando Cejas, Mobile Director @Wire, @SoundCloud Alumni, former @IBM Developer Advocate @IBM and @Tuenti Alumni.
I'm  a geek/nerd, huge fan of Mobile Development, Artificial Intelligence, Quantum Computing and Software Engineering in general. 
Here I share my experiences and expose my ideas: all views, posts and opinions are my own."
meta_description: "Welcome! I'm Fernando Cejas, Director of Mobile @Wire, @SoundCloud Alumni, former @IBM Developer and @Tuenti Alumni. I'm  a geek/nerd, huge fan of Mobile Development, Artificial Intelligence, Quantum Computing and Software Engineering in general. Here I share my experiences and expose my ideas but all views, posts and opinions are my own."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-17189586-4'
disqus: 'fernandocejas'
mailchimp-list: 'https://fernandocejas.us19.list-manage.com/subscribe/post?u=dbfbeb86419b7deba2c2e951d&amp;id=80bff95534'

# Authors
authors:
  fernando:
    name: Fernando
    display_name: Fernando
    gravatar: 12defde716586eb2d726d081a161756d
    email: fcejas@gmail.com
    web: https://www.fernandocejas.com
    twitter: https://twitter.com/fernando_cejas
    description: "Director of Mobile at @Wire. @SoundCloud Alumni. Former @IBM Developer Advocate. Curious Learner. Leadershing and Engineering. Nerdy Geek. Quantum Computing and Science fan."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
